# Coniguraci\u00F3n de la Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/consultorio_medico?useSSL=false
spring.datasource.username=root
spring.datasource.password=

# Configuracion de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update

server.port=8080
